#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 01.10.2021 13:05
# Generated By: Dimitrije TBZ
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$btn_zuruecksetzen = New-Object System.Windows.Forms.Button
$grb_wiederherstellung = New-Object System.Windows.Forms.GroupBox
$ckb_nachw = New-Object System.Windows.Forms.CheckBox
$ckb_wvorher = New-Object System.Windows.Forms.CheckBox
$grb_farbe = New-Object System.Windows.Forms.GroupBox
$ckb_darkmode = New-Object System.Windows.Forms.CheckBox
$btn_standardfarbeloeschen = New-Object System.Windows.Forms.Button
$btn_standardfarbe = New-Object System.Windows.Forms.Button
$grb_applikation = New-Object System.Windows.Forms.GroupBox
$ckb_chocolatey = New-Object System.Windows.Forms.CheckBox
$lbl_browser = New-Object System.Windows.Forms.Label
$ckb_firefox = New-Object System.Windows.Forms.CheckBox
$ckb_opera = New-Object System.Windows.Forms.CheckBox
$ckb_chrome = New-Object System.Windows.Forms.CheckBox
$lbl_archiv = New-Object System.Windows.Forms.Label
$ckb_winrar = New-Object System.Windows.Forms.CheckBox
$ckb_7zip = New-Object System.Windows.Forms.CheckBox
$lbl_chat = New-Object System.Windows.Forms.Label
$ckb_download = New-Object System.Windows.Forms.CheckBox
$ckb_backup = New-Object System.Windows.Forms.CheckBox
$ckb_geek = New-Object System.Windows.Forms.CheckBox
$ckb_teams = New-Object System.Windows.Forms.CheckBox
$ckb_discord = New-Object System.Windows.Forms.CheckBox
$ckb_zoom = New-Object System.Windows.Forms.CheckBox
$lbl_sonstige = New-Object System.Windows.Forms.Label
$lbl_medien = New-Object System.Windows.Forms.Label
$ckb_adobe = New-Object System.Windows.Forms.CheckBox
$ckb_paintnet = New-Object System.Windows.Forms.CheckBox
$ckb_vlc = New-Object System.Windows.Forms.CheckBox
$grb_benutzer = New-Object System.Windows.Forms.GroupBox
$ckb_user = New-Object System.Windows.Forms.CheckBox
$txb_nachname = New-Object System.Windows.Forms.TextBox
$lbl_nachname = New-Object System.Windows.Forms.Label
$ckb_passaendern = New-Object System.Windows.Forms.CheckBox
$ckb_aktiv = New-Object System.Windows.Forms.CheckBox
$txb_pass = New-Object System.Windows.Forms.TextBox
$lbl_pass = New-Object System.Windows.Forms.Label
$txb_user = New-Object System.Windows.Forms.TextBox
$lbl_user = New-Object System.Windows.Forms.Label
$txb_vorname = New-Object System.Windows.Forms.TextBox
$lbl_vorname = New-Object System.Windows.Forms.Label
$grb_name = New-Object System.Windows.Forms.GroupBox
$ckb_name = New-Object System.Windows.Forms.CheckBox
$txb_name = New-Object System.Windows.Forms.TextBox
$lbl_name = New-Object System.Windows.Forms.Label
$checkBox1 = New-Object System.Windows.Forms.CheckBox
$lsb_log = New-Object System.Windows.Forms.ListBox
$btn_laden = New-Object System.Windows.Forms.Button
$btn_speichern = New-Object System.Windows.Forms.Button
$btn_anwenden = New-Object System.Windows.Forms.Button
$grb_hintergrund = New-Object System.Windows.Forms.GroupBox
$lbl_hintergrund = New-Object System.Windows.Forms.Label
$txb_url = New-Object System.Windows.Forms.TextBox
$btn_hintergrund = New-Object System.Windows.Forms.Button
$ckb_hintergrund = New-Object System.Windows.Forms.CheckBox
$img_hintergrund = New-Object System.Windows.Forms.PictureBox
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
$frm_neustart = New-Object System.Windows.Forms.Form
$lbl_neustart = New-Object System.Windows.Forms.Label
$btn_spaeter = New-Object System.Windows.Forms.Button
$btn_neustarten = New-Object System.Windows.Forms.Button
$frm_pass = New-Object System.Windows.Forms.Form
$btn_OKpass = New-Object System.Windows.Forms.Button
$lbl_passmeldung = New-Object System.Windows.Forms.Label
$frm_bildladen = New-Object System.Windows.Forms.Form
$btn_OKbild = New-Object System.Windows.Forms.Button
$lbl_bildladen = New-Object System.Windows.Forms.Label
$frm_farbe = New-Object System.Windows.Forms.Form
$lbl_farbe = New-Object System.Windows.Forms.Label
$btn_grau = New-Object System.Windows.Forms.Button
$btn_rot = New-Object System.Windows.Forms.Button
$btn_gelb = New-Object System.Windows.Forms.Button
$btn_violett = New-Object System.Windows.Forms.Button
$btn_gruen = New-Object System.Windows.Forms.Button
$btn_blau = New-Object System.Windows.Forms.Button
$frm_pcname = New-Object System.Windows.Forms.Form
$btn_okpcname = New-Object System.Windows.Forms.Button
$lbl_pcname = New-Object System.Windows.Forms.Label
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$RegPath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Accent"          #Pfad für Farbe im Regedit
$nummer = Get-Random                                                                  #Zufällige Zahl
$pfad = "C:\Windows\Temp\" + $nummer + ".jpg"                                         #Pfad bei den die Bilder gespeichert werden
$lsb_log.Items.Add("Chocolatey wird installiert...")
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
$lsb_log.Items.Add("Chocolatey wurde installiert")
Function Set-WallPaper($Image) {
  
Add-Type -TypeDefinition @" 
using System; 
using System.Runtime.InteropServices;
  
public class Params
{ 
    [DllImport("User32.dll",CharSet=CharSet.Unicode)] 
    public static extern int SystemParametersInfo (Int32 uAction, 
                                                   Int32 uParam, 
                                                   String lpvParam, 
                                                   Int32 fuWinIni);
}
"@ 
  
    $SPI_SETDESKWALLPAPER = 0x0014
    $UpdateIniFile = 0x01
    $SendChangeEvent = 0x02
  
    $fWinIni = $UpdateIniFile -bor $SendChangeEvent
  
    $ret = [Params]::SystemParametersInfo($SPI_SETDESKWALLPAPER, 0, $Image, $fWinIni)
 
}
 
                                                          
$ckb_chocolatey.Checked = $True
$ckb_chocolatey.Enabled = $False

$btn_spaeter_OnClick=                                                                       #Wenn bei $frm_neustart auf später gedrückt wird, wird das Fenster $frm_neustart geschlossen
{
#TODO: Place custom script here

$frm_neustart.Close()


}

$btn_okpcname_OnClick=                                                                     #Wenn bei $frm_pcname auf OK gedrückt wird, wird das Fenster $frm_pcname geschlossen                                                               
{
#TODO: Place custom script here
$frm_pcname.Close()

}

$btn_OKbild_OnClick=                                                                       #Wenn bei $frm_bildladen auf später gedrückt wird, wird das Fenster $frm_neustart geschlossen
{
$frm_bildladen.Close()

}

$btn_neustarten_OnClick=                                                                   #Wenn bei $frm_neustart auf neustarten gedrückt wird, wird das PC neugestartet
{
#TODO: Place custom script here

Restart-Computer

}

$btn_speichern_OnClick= 
{
#TODO: Place custom script here
$lsb_log.Items.Add("Konfiguration wird gespeichert")
$kurl = $txb_url.Text                                                                      #Speichert der Status (ausgewählt/text) in eine Andere Variable
$kopera = $ckb_opera.Checked
$kfirefox = $ckb_firefox.Checked
$kchrome = $ckb_chrome.Checked
$kdiscord = $ckb_discord.Checked
$kteams = $ckb_teams.Checked
$kgeek = $ckb_geek.Checked
$kbackup = $ckb_backup.Checked
$kdownloader = $ckb_download.Checked
$kadobe = $ckb_adobe.Checked
$kvlc = $ckb_vlc.checked
$kpaint = $ckb_paintnet.Checked
$kzoom = $ckb_zoom.Checked
$k7zip = $ckb_7zip.Checked
$kwinrar = $ckb_winrar.Checked
$khintergrund = $ckb_hintergrund.Checked
$kpcname = $ckb_name.Checked
$kbenutzer = $ckb_user.Checked
$kdarkmode = $ckb_darkmode.checked
$kwvorher = $ckb_wvorher.Checked
$kwnacher = $ckb_nachw.Checked
$kfarbe = $btn_standardfarbe.BackColor
$kbenutzeraktiv = $ckb_aktiv.Checked
$kbenutzerpassaendern = $ckb_passaendern.Checked
$ktpcname = $txb_name.Text
$ktbenutzerv = $txb_vorname.Text
$ktbenutzern = $txb_nachname.Text
$ktuser = $txb_user.Text
$ktpass = $txb_pass.Text

$konfigurationspeichern = New-Object System.Windows.Forms.FolderBrowserDialog
$konfigurationspeichern.Description = "Waehlen Sie wo die Konfigurationsdatei gespeichert werden soll"    #Text bei der Explorer Fenster
$konfigurationspeichern.rootfolder = "MyComputer"

[XML]$xml = "<konfiguration> <firefox>$kfirefox</firefox> <chrome>$kchrome</chrome><discord>$kdiscord</discord><teams>$kteams</teams><geek>$kgeek</geek><backup>$kbackup</backup><downloader>$kdownloader</downloader><adobe>$kadobe</adobe><vlc>$kvlc</vlc><paint>$kpaint</paint><zoom>$kzoom</zoom><zip>$k7zip</zip><winrar>$kwinrar</winrar><hintergrund>$khintergrund</hintergrund><pcname>$kpcname</pcname><benutzer>$kbenutzer</benutzer><darkmode>$kdarkmode</darkmode><wvorher>$kwvorher</wvorher><wnacher>$kwnacher</wnacher><farbe>$kfarbe</farbe><aktiv>$kbenutzeraktiv</aktiv><benutzerpassaendern>$kbenutzerpassaendern</benutzerpassaendern><tpcname>$ktpcname</tpcname><tbenutzerv>$ktbenutzerv</tbenutzerv><tbenutzern>$ktbenutzern</tbenutzern><tuser>$ktuser</tuser><tpass>$ktpass</tpass><url>$kurl</url><opera>$kopera</opera></konfiguration> "  #Variable mit alle Variabeln für die Konfiguration

   if($konfigurationspeichern.ShowDialog() -eq "OK")                                                      #Wenn OK gedrückt wird, wird der Pfad vom ausgewählten Ordner im Textbox angezeigt
    {
        $xml.save($konfigurationspeichern.SelectedPath + "konfiguration.xml")                             #Wird in eine XML Datei gespeichert

    }

$lsb_log.Items.Add("Konfiguration wurde gespeichert")


}


#Region aktivieren/deaktivieren
$txb_url.Enabled = $False                                                                   #Textboxen und Checkboxen werden deaktiviert
$btn_hintergrund.Enabled = $false
$img_hintergrund.Enabled = $false
$txb_nachname.Enabled = $false
$txb_vorname.Enabled = $false
$txb_pass.Enabled = $false
$txb_user.Enabled = $false
$ckb_aktiv.Enabled = $false
$ckb_passaendern.Enabled = $false
$txb_name.Enabled = $False

$ckb_hintergrund.Add_CheckedChanged({                                                       #Wenn Checkbox Hintergrund aktiviert/deaktiviert wird, Werden die Spezifischen Checkboxen und Textboxen aktiviert/deaktiviert
if ($ckb_hintergrund.Checked -eq $true){
        $txb_url.Enabled = $true
        $btn_hintergrund.Enabled = $true
        $img_hintergrund.Enabled = $true
    }else{
        $txb_url.Enabled = $false
        $btn_hintergrund.Enabled = $false
        $img_hintergrund.Enabled = $false
    }
})

$ckb_user.Add_CheckedChanged({                                                             #Wenn Checkbox User aktiviert/deaktiviert wird, Werden die Spezifischen Checkboxen und Textboxen aktiviert/deaktiviert

if($ckb_user.Checked -eq $true){
        $txb_nachname.Enabled = $true
        $txb_vorname.Enabled = $true
        $txb_pass.Enabled = $true
        $txb_user.Enabled = $true
        $ckb_aktiv.Enabled = $true
        $ckb_passaendern.Enabled = $true
    }else{
        $txb_nachname.Enabled = $false
        $txb_vorname.Enabled = $false
        $txb_pass.Enabled = $false
        $txb_user.Enabled = $false
        $ckb_aktiv.Enabled = $false
        $ckb_passaendern.Enabled = $false
    }
})

$ckb_name.Add_CheckedChanged({                                                             #Wenn Checkbox Name aktiviert/deaktiviert wird, Werden die Spezifischen Checkboxen und Textboxen aktiviert/deaktiviert

if($ckb_name.Checked -eq $True){
        $txb_name.Enabled = $True
    }else{
        $txb_name.Enabled = $False
    }
})


$handler_txb_url_TextChanged= 
{
#TODO: Place custom script here

}



$handler_lsb_log_SelectedIndexChanged= 
{
#TODO: Place custom script here

}

$handler_lbl_hintergrund_Click= 
{
#TODO: Place custom script here

}

$handler_label2_Click= 
{
#TODO: Place custom script here

}

$btn_gelb_OnClick=                                                                         #Wenn die gelbe Farbe ausgewählt wird, wechselt der Standardbutton zu diese Farbe 
{
#TODO: Place custom script here
$frm_farbe.Close()
$btn_standardfarbe.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,0)
}

$btn_gruen_OnClick=                                                                        #Wenn die gruene Farbe ausgewählt wird, wechselt der Standardbutton zu diese Farbe
{
#TODO: Place custom script here
$frm_farbe.Close()
$btn_standardfarbe.BackColor = [System.Drawing.Color]::FromArgb(255,0,255,0)

}

$btn_violett_OnClick=                                                                      #Wenn die violette Farbe ausgewählt wird, wechselt der Standardbutton zu diese Farbe
{
#TODO: Place custom script here
$frm_farbe.Close()
$btn_standardfarbe.BackColor = [System.Drawing.Color]::FromArgb(255,238,130,238)
}

$btn_blau_OnClick=                                                                         #Wenn die blaue Farbe ausgewählt wird, wechselt der Standardbutton zu diese Farbe
{
#TODO: Place custom script here
$frm_farbe.Close()
$btn_standardfarbe.BackColor = [System.Drawing.Color]::FromArgb(255,30,144,255)
}

$btn_rot_OnClick=                                                                          #Wenn die rote Farbe ausgewählt wird, wechselt der Standardbutton zu diese Farbe
{
#TODO: Place custom script here
$frm_farbe.Close()
$btn_standardfarbe.BackColor = [System.Drawing.Color]::FromArgb(255,255,0,0)
}

$btn_grau_OnClick=                                                                         #Wenn die graue Farbe ausgewählt wird, wechselt der Standardbutton zu diese Farbe
{
#TODO: Place custom script here
$frm_farbe.Close()
$btn_standardfarbe.BackColor = [System.Drawing.Color]::FromArgb(255,169,169,169)
}

$btn_standardfarbe_OnClick=                                                                #Wird die $frm_farbe geöffnet
{
#TODO: Place custom script here
$frm_farbe.ShowDialog() | Out-Null

}

$btn_laden_OnClick= 
{
#TODO: Place custom script here
$lsb_log.Items.Add("Konfiguration wird geladen")
$konfigurationladen = New-Object System.Windows.Forms.OpenFileDialog -Property @{
    Multiselect = $false 
	Filter = 'XML Files (*.xml)|*.xml' 
}
$konfigurationladen.ShowDialog()

$xml = Get-Content $konfigurationladen.FileName                                            #Wird der Inhalt der Datei genommen
$xmlauswertung = [xml]$xml                                                                 #Wird die XML Datei ausgewertet
if($xmlauswertung.konfiguration.opera -eq "False"){$ckb_opera.Checked = $false}else{$ckb_opera.Checked = $True}                                   #Wenn der Wert False oder True ist, dann wird es in der GUI auch so angezeigt                                    
if($xmlauswertung.konfiguration.firefox -eq "False"){$ckb_firefox.Checked = $false}else{$ckb_firefox.Checked = $True}
if($xmlauswertung.konfiguration.chrome -eq "False"){$ckb_chrome.Checked = $false}else{$ckb_chrome.Checked = $True}
if($xmlauswertung.konfiguration.discord -eq "False"){$ckb_discord.Checked = $false}else{$ckb_discord.Checked = $True}
if($xmlauswertung.konfiguration.teams -eq "False"){$ckb_teams.Checked = $false}else{$ckb_teams.Checked = $True}
if($xmlauswertung.konfiguration.geek -eq "False"){$ckb_geek.Checked = $false}else{$ckb_geek.Checked = $True}
if($xmlauswertung.konfiguration.backup -eq "False"){$ckb_backup.Checked = $false}else{$ckb_backup.Checked = $True}
if($xmlauswertung.konfiguration.downloader -eq "False"){$ckb_download.Checked = $false}else{$ckb_download.Checked = $True}
if($xmlauswertung.konfiguration.adobe -eq "False"){$ckb_adobe.Checked = $false}else{$ckb_adobe.Checked = $True}
if($xmlauswertung.konfiguration.vlc -eq "False"){$ckb_vlc.checked = $false}else{$ckb_vlc.checked = $True}
if($xmlauswertung.konfiguration.paint -eq "False"){$ckb_paintnet.Checked = $false}else{$ckb_paintnet.Checked = $True}
if($xmlauswertung.konfiguration.zoom -eq "False"){$ckb_zoom.Checked = $false}else{$ckb_zoom.Checked = $True}
if($xmlauswertung.konfiguration.zip -eq "False"){$ckb_7zip.Checked = $false}else{$ckb_7zip.Checked = $True}
if($xmlauswertung.konfiguration.winrar -eq "False"){$ckb_winrar.Checked = $false}else{$ckb_winrar.Checked = $True}
if($xmlauswertung.konfiguration.hintergrund -eq "False"){$ckb_hintergrund.Checked = $false}else{$ckb_hintergrund.Checked = $True}
if($xmlauswertung.konfiguration.pcname -eq "False"){$ckb_name.Checked = $false}else{$ckb_name.Checked = $True}
if($xmlauswertung.konfiguration.benutzer -eq "False"){$ckb_user.Checked = $false}else{$ckb_user.Checked = $True}
if($xmlauswertung.konfiguration.darkmode -eq "False"){$ckb_darkmode.checked = $false}else{$ckb_darkmode.checked = $True}
if($xmlauswertung.konfiguration.wvorher -eq "False"){$ckb_wvorher.Checked = $false}else{$ckb_wvorher.Checked = $True}
if($xmlauswertung.konfiguration.wnacher -eq "False"){$ckb_nachw.Checked = $false}else{$ckb_nachw.Checked = $True}
if($xmlauswertung.konfiguration.aktiv -eq "False"){$ckb_aktiv.Checked = $false}else{$ckb_aktiv.Checked = $True}
if($xmlauswertung.konfiguration.benutzerpassaendern -eq "False"){$ckb_passaendern.Checked = $false}else{$ckb_passaendern.Checked = $True}
$txb_url.Text = $xmlauswertung.konfiguration.url                                                                                                  #Der Text wird in der GUI gesetzt/geschrieben
#$btn_standardfarbe.BackColor = $xmlauswertung.konfiguration.farbe
#$xmlfarbe = $xmlauswertung.konfiguration.farbe -replace '\D+(\d+)','$1'
$farbec = $xmlauswertung.konfiguration.farbe -replace "Color "
$farber = $farbec -replace "R="
$farbeg = $farber -replace "G="
$farbeb = $farbeg -replace "B="
$farbeklammer = $farbeb -replace ".{1}$"
$farbeklammer1 = $farbeklammer -replace '[[\]{}''"]'
$farbea = $farbeklammer1 -replace "A="
$farbef = $farbea -replace "\s", ""
if ($farbef -eq "255,238,130,238"){
$btn_standardfarbe.BackColor = [System.Drawing.Color]::FromArgb(255,238,130,238)
}elseif($farbef -eq "255,255,255,0"){
$btn_standardfarbe.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,0)
}elseif($farbef -eq "255,0,255,0"){
$btn_standardfarbe.BackColor = [System.Drawing.Color]::FromArgb(255,0,255,0)
}elseif($farbef -eq "255,30,144,255"){
$btn_standardfarbe.BackColor = [System.Drawing.Color]::FromArgb(255,30,144,255)
}elseif($farbef -eq "255,255,0,0"){
$btn_standardfarbe.BackColor = [System.Drawing.Color]::FromArgb(255,255,0,0)
}elseif($farbef -eq "255,169,169,169"){
$btn_standardfarbe.BackColor = [System.Drawing.Color]::FromArgb(255,169,169,169)
}elseif($farbef -eq "255,255,255,255"){}


#$btn_standardfarbe.BackColor = [System.Drawing.Color]::FromArgb($farbef)
$txb_name.Text = $xmlauswertung.konfiguration.tpcname
$txb_vorname.Text = $xmlauswertung.konfiguration.tbenutzerv
$txb_nachname.Text = $xmlauswertung.konfiguration.tbenutzern
$txb_user.Text = $xmlauswertung.konfiguration.tuser
$txb_pass.Text = $xmlauswertung.konfiguration.tpass
$lsb_log.Items.Add("Konfiguration wurde geladen")
}

$handler_pictureBox2_Click= 
{
#TODO: Place custom script here

}

$handler_label8_Click= 
{
#TODO: Place custom script here

}

$handler_ckb_vlc_CheckedChanged= 
{
#TODO: Place custom script here

}

$btn_OKpass_OnClick=                                                             #Wenn bei $frm_pass auf OK gedrückt wird, wird das Fenster $frm_pass geschlossen
{
#TODO: Place custom script here
$frm_pass.Close()
}

$btn_standardfarbeloeschen_OnClick=                                              #Wird die Farbe in der Button zurückgesetzt (standardfarbe)  
{
#TODO: Place custom script here
$btn_standardfarbe.UseVisualStyleBackColor = $True
}

$btn_anwenden_OnClick=                                                           #Wenn Anwenden gedrückt wird, wird alles, was eingestellt ist, ausgeführt
{
#TODO: Place custom script here

if($ckb_wvorher.Checked -eq $true){                                              #Wird ein Wiederherstellungspunkt erstellt

$datum = Get-Date

Checkpoint-Computer -Description $datum 

}


if($ckb_chocolatey.Checked -eq $True){                                          #Werden die ausgewählten Programme installiert

}

if($ckb_opera.Checked -eq $True){
    $lsb_log.Items.Add("Opera wird installiert...")
    choco install opera -y
    $lsb_log.Items.Add("Opera wurde installiert")
}

if($ckb_chrome.Checked -eq $true){
    $lsb_log.Items.Add("Google Chrome wird installiert...")
    choco install googlechrome
    $lsb_log.Items.Add("Google Chrome wurde installiert")
}

if($ckb_winrar.Checked -eq $True){
    $lsb_log.Items.Add("WinRar wird installiert...")
    choco install winrar -y
    $lsb_log.Items.Add("WinRar wurde installiert")
}

if($ckb_7zip.Checked -eq $True){
    $lsb_log.Items.Add("7-Zip wird installiert...")
    choco install 7zip -y
    $lsb_log.Items.Add("7-Zip wurde installiert...")
}

if($ckb_firefox.Checked -eq $true){
    $lsb_log.Items.Add("Firefox wird installiert...")
    choco install firefox
    $lsb_log.Items.Add("Firefox wurde installiert")
}

if($ckb_teams.Checked -eq $True){
    $lsb_log.Items.Add("Microsoft Teams wird installiert...")
    choco install microsoft-teams -y
    $lsb_log.Items.Add("Microsoft Teams wurde installiert")
}

if($ckb_discord.Checked -eq $True){
    $lsb_log.Items.Add("Discord wird installiert...")
    choco install discord -y
    $lsb_log.Items.Add("Discord wurde installiert")
}

if($ckb_zoom.Checked -eq $True){
    $lsb_log.Items.Add("Zoom wird installiert...")
    choco install zoom
    $lsb_log.Items.Add("Zoom wurde installiert")
}

if($ckb_geek.Checked -eq $True){
    $lsb_log.Items.Add("Geekuninstaller wird installiert...")
    choco install geekuninstaller -y
    $lsb_log.Items.Add("Geekuninstaller wurde installiert")
}

if($ckb_adobe.Checked -eq $True){
    $lsb_log.Items.Add("Adobe Reader wird installiert...")
    choco install adobereader -y
    $lsb_log.Items.Add("Adobe Reader wurde installiert")
}

if($ckb_download.Checked -eq $True){
    $lsb_log.Items.Add("FreeDownloadManager wird installiert...")
    choco install freedownloadmanager -y
    $lsb_log.Items.Add("FreeDownloadManager wurde installiert")
}

if($ckb_paintnet.Checked -eq $true){
    $lsb_log.Items.Add("Paint.Net wird installiert...")
    choco install paint.net -y
    $lsb_log.Items.Add("Paint.Net wurde installiert")
}

if($ckb_vlc.Checked -eq $True){
    $lsb_log.Items.Add("VLC wird installiert...")
    choco install vlc -y
    $lsb_log.Items.Add("VLC wurde installiert")
}

if($ckb_backup.Checked -eq $true){
    $lsb_log.Items.Add("Google Backup and Sync wird installiert...")
    choco install google-backup-and-sync -y
    $lsb_log.Items.Add("Google Backup and Sync wurde installiert")
}


if ($ckb_name.Checked -eq $True){                                         #Wird der PC Name geändert

    $lsb_log.Items.Add("PC-Name wird geändert")   
    try{
        Rename-Computer -NewName $txb_name.Text -ErrorAction stop
        $frm_neustart.ShowDialog()| Out-Null
        $lsb_log.Items.Add("PC-Name wurde geändert")
    
    }catch {
        $frm_pcname.ShowDialog()                                              
        $lsb_log.Items.Add("PC-Name konnte nicht geändert werden")
    
    } 

}

if($btn_standardfarbe.UseVisualStyleBackColor = $True){}                 #Wenn bei der Button die standard Farbe eingestellt ist, wird nichts gemacht

$blau = [System.Drawing.Color]::FromArgb(255,30,144,255)
if($btn_standardfarbe.BackColor -eq $blau){                              #Wenn bei der Button die Blaue Farbe eingestellt ist, wird die Windows Farbe geändert. Dabei werden Werten im Regedit geändert, das heisst, dass man Windows nicht zwingend Aktivieren muss


#Accent Color Menu Key
$AccentColorMenuKey = @{                                                 #Wird die Farbe beim Menü geändert
	Key   = 'AccentColorMenu';
	Type  = "DWORD";
	Value = '0xff4e3f30'                                        
}

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -Value $AccentColorMenuKey.Value -PropertyType $AccentColorMenuKey.Type -Force
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -Value $AccentColorMenuKey.Value -Force
}


#Accent Palette Key
$AccentPaletteKey = @{                                                  #Wird den Wert bei den Palette geändert
	Key   = 'AccentPalette';
	Type  = "BINARY";
	Value = '51,6b,84,ff,43,59,6e,ff,3a,4c,5e,ff,30,3f,4e,ff,26,33,3f,ff,1d,26,2f,ff,0f,14,19,ff,88,17,98,00'
}
$hexified = $AccentPaletteKey.Value.Split(',') | ForEach-Object { "0x$_" }

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -PropertyType Binary -Value ([byte[]]$hexified)
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -Value ([byte[]]$hexified) -Force
}


#Start Color Menu Key
$StartMenuKey = @{                                                      #Wird die start Farbe geändert
	Key   = 'StartColorMenu';
	Type  = "DWORD";
	Value = '0xff3f3326'
}

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -Value $StartMenuKey.Value -PropertyType $StartMenuKey.Type -Force
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -Value $StartMenuKey.Value -Force
}


Stop-Process -ProcessName explorer -Force -ErrorAction SilentlyContinue


}
$grau = [System.Drawing.Color]::FromArgb(255,169,169,169)
if($btn_standardfarbe.BackColor -eq $grau){                                #Wenn bei der Button die Graue Farbe eingestellt ist, wird die Windows Farbe geändert. Dabei werden Werten im Regedit geändert, das heisst, dass man Windows nicht zwingend Aktivieren muss

#Accent Color Menu Key
$AccentColorMenuKey = @{
	Key   = 'AccentColorMenu';
	Type  = "DWORD";
	Value = '0xff74757a'
}

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -Value $AccentColorMenuKey.Value -PropertyType $AccentColorMenuKey.Type -Force
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -Value $AccentColorMenuKey.Value -Force
}


#Accent Palette Key
$AccentPaletteKey = @{
	Key   = 'AccentPalette';
	Type  = "BINARY";
	Value = 'd9,d1,ce,00,c8,c0,be,00,a7,a0,9f,00,7a,75,74,00,5f,5b,5a,00,39,36,36,00,26,25,25,00,ea,00,5e,00'
}
$hexified = $AccentPaletteKey.Value.Split(',') | ForEach-Object { "0x$_" }

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -PropertyType Binary -Value ([byte[]]$hexified)
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -Value ([byte[]]$hexified) -Force
}



#Start Color Menu Key
$StartMenuKey = @{
	Key   = 'StartColorMenu';
	Type  = "DWORD";
	Value = '0xff5a5b5f'
}

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -Value $StartMenuKey.Value -PropertyType $StartMenuKey.Type -Force
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -Value $StartMenuKey.Value -Force
}


Stop-Process -ProcessName explorer -Force -ErrorAction SilentlyContinue
}
$rot = [System.Drawing.Color]::FromArgb(255,255,0,0)              #Wenn bei der Button die Rote Farbe eingestellt ist, wird die Windows Farbe geändert. Dabei werden Werten im Regedit geändert, das heisst, dass man Windows nicht zwingend Aktivieren muss
if($btn_standardfarbe.BackColor -eq $rot){

#Accent Color Menu Key
$AccentColorMenuKey = @{
	Key   = 'AccentColorMenu';
	Type  = "DWORD";
	Value = '0xff2311e8'
}

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -Value $AccentColorMenuKey.Value -PropertyType $AccentColorMenuKey.Type -Force
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -Value $AccentColorMenuKey.Value -Force
}


#Accent Palette Key
$AccentPaletteKey = @{
	Key   = 'AccentPalette';
	Type  = "BINARY";
	Value = 'ff,bd,c2,00,ff,99,a1,00,f0,59,65,00,e8,11,23,00,99,00,0d,00,6e,00,09,00,47,00,06,00,69,79,7e,00'
}
$hexified = $AccentPaletteKey.Value.Split(',') | ForEach-Object { "0x$_" }

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -PropertyType Binary -Value ([byte[]]$hexified)
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -Value ([byte[]]$hexified) -Force
}



#Start Color Menu Key
$StartMenuKey = @{
	Key   = 'StartColorMenu';
	Type  = "DWORD";
	Value = '0xff0d0099'
}

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -Value $StartMenuKey.Value -PropertyType $StartMenuKey.Type -Force
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -Value $StartMenuKey.Value -Force
}


Stop-Process -ProcessName explorer -Force -ErrorAction SilentlyContinue

}
$violett = [System.Drawing.Color]::FromArgb(255,238,130,238)            #Wenn bei der Button die Violette Farbe eingestellt ist, wird die Windows Farbe geändert. Dabei werden Werten im Regedit geändert, das heisst, dass man Windows nicht zwingend Aktivieren muss
if($btn_standardfarbe.BackColor -eq $violett){

#Accent Color Menu Key
$AccentColorMenuKey = @{
	Key   = 'AccentColorMenu';
	Type  = "DWORD";
	Value = '0xffb339c2'
}

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -Value $AccentColorMenuKey.Value -PropertyType $AccentColorMenuKey.Type -Force
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -Value $AccentColorMenuKey.Value -Force
}


#Accent Palette Key
$AccentPaletteKey = @{
	Key   = 'AccentPalette';
	Type  = "BINARY";
	Value = 'ff,ab,f5,00,e9,89,de,00,cf,62,c3,00,c2,39,b3,00,8c,29,81,00,63,1d,5b,00,3b,08,36,00,2d,7d,9a,00'
}
$hexified = $AccentPaletteKey.Value.Split(',') | ForEach-Object { "0x$_" }

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -PropertyType Binary -Value ([byte[]]$hexified)
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -Value ([byte[]]$hexified) -Force
}



#Start Color Menu Key
$StartMenuKey = @{
	Key   = 'StartColorMenu';
	Type  = "DWORD";
	Value = '0xff81298c'
}

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -Value $StartMenuKey.Value -PropertyType $StartMenuKey.Type -Force
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -Value $StartMenuKey.Value -Force
}


Stop-Process -ProcessName explorer -Force -ErrorAction SilentlyContinue

}
$gelb = [System.Drawing.Color]::FromArgb(255,255,255,0)
if($btn_standardfarbe.BackColor -eq $gelb){                          #Wenn bei der Button die Gelbe Farbe eingestellt ist, wird die Windows Farbe geändert. Dabei werden Werten im Regedit geändert, das heisst, dass man Windows nicht zwingend Aktivieren muss

#Accent Color Menu Key
$AccentColorMenuKey = @{
	Key   = 'AccentColorMenu';
	Type  = "DWORD";
	Value = '0xff00b9ff'
}

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -Value $AccentColorMenuKey.Value -PropertyType $AccentColorMenuKey.Type -Force
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -Value $AccentColorMenuKey.Value -Force
}


#Accent Palette Key
$AccentPaletteKey = @{
	Key   = 'AccentPalette';
	Type  = "BINARY";
	Value = 'ff,e8,a8,00,ff,e0,8c,00,ff,d3,5c,00,ff,b9,00,00,ba,89,00,00,80,5e,00,00,4d,38,00,00,00,b2,94,00'
}
$hexified = $AccentPaletteKey.Value.Split(',') | ForEach-Object { "0x$_" }

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -PropertyType Binary -Value ([byte[]]$hexified)
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -Value ([byte[]]$hexified) -Force
}



#Start Color Menu Key
$StartMenuKey = @{
	Key   = 'StartColorMenu';
	Type  = "DWORD";
	Value = '0xff0089ba'
}

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -Value $StartMenuKey.Value -PropertyType $StartMenuKey.Type -Force
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -Value $StartMenuKey.Value -Force
}


Stop-Process -ProcessName explorer -Force -ErrorAction SilentlyContinue

}
$gruen = [System.Drawing.Color]::FromArgb(255,0,255,0)
if($btn_standardfarbe.BackColor -eq $gruen){          #Wenn bei der Button die Gruene Farbe eingestellt ist, wird die Windows Farbe geändert. Dabei werden Werten im Regedit geändert, das heisst, dass man Windows nicht zwingend Aktivieren muss

#Accent Color Menu Key
$AccentColorMenuKey = @{
	Key   = 'AccentColorMenu';
	Type  = "DWORD";
	Value = '0xff6acc00'
}

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -Value $AccentColorMenuKey.Value -PropertyType $AccentColorMenuKey.Type -Force
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $AccentColorMenuKey.Key -Value $AccentColorMenuKey.Value -Force
}


#Accent Palette Key
$AccentPaletteKey = @{
	Key   = 'AccentPalette';
	Type  = "BINARY";
	Value = 'c1,f7,dd,00,a6,f7,d0,00,68,e3,a8,00,00,cc,6a,00,00,87,46,00,00,52,2a,00,00,2b,16,00,e3,00,80,00
'
}
$hexified = $AccentPaletteKey.Value.Split(',') | ForEach-Object { "0x$_" }

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -PropertyType Binary -Value ([byte[]]$hexified)
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $AccentPaletteKey.Key -Value ([byte[]]$hexified) -Force
}



#Start Color Menu Key
$StartMenuKey = @{
	Key   = 'StartColorMenu';
	Type  = "DWORD";
	Value = '0xff468700'
}

If ($Null -eq (Get-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -ErrorAction SilentlyContinue))
{
	New-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -Value $StartMenuKey.Value -PropertyType $StartMenuKey.Type -Force
}
Else
{
	Set-ItemProperty -Path $RegPath -Name $StartMenuKey.Key -Value $StartMenuKey.Value -Force
}


Stop-Process -ProcessName explorer -Force -ErrorAction SilentlyContinue

}



if($ckb_darkmode.Checked -eq $True){
$lsb_log.Items.Add("Darkmodus wird eingestellt...")
"Set-ItemProperty -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize -Name AppsUseLightTheme -Value 0" > C:\darkmode.ps1     #Wird ein separates Skript erstellt, weil sonst der Programm abstürzen würde. Dabei wird ein Wert im Regedit geändert
C:\darkmode.ps1
$lsb_log.Items.Add("Darkmodus wurde eingestellt")
}

if($ckb_user.Checked -eq $True){
$lsb_log.Items.Add("Lokale Benutzer wird erstellt...")
try{                                                                                              #Wird versucht ein Benutzer zu erstellen

$pass = ConvertTo-SecureString $txb_pass.text -AsPlainText -force                                 #Passwort wird im SecureString convertiert
$fullname = $txb_vorname.Text + " " + $txb_nachname.Text                                          #Ganzer Name
New-LocalUser $txb_user.Text -Password $pass -FullName $fullname                                  #Neues Benutzer mit den eingegebenen Passwort und ganzer Name wird erstellt

if($ckb_aktiv.Checked -eq $true){                                                                 #Benutzer wird aktiviert

Enable-LocalUser -name $txb_user.Text

}else{

Disable-LocalUser -name $txb_user.Text                                                           #Benutzer wird deaktiviert

}

if($ckb_passaendern.Checked -eq $True){

Set-LocalUser -Name $txb_user.Text -UserMayChangePassword $false                                 #Benutzer kann das Passwort nicht ändern

}

$lsb_log.Items.Add("Lokale Benutzer wurde erstellt")

}catch{                                                                                          #Wenn Benutzer nicht erstellt werden konnte, öffnet sich die Fenster $frm_pass


$frm_pass.ShowDialog()| Out-Null
$lsb_log.Items.Add("Lokale Benutzer konnte nicht erstellt werden")
}

}

if($txb_url.Text -ne "" ){                                                                       #Wenn bei der Textbox vom Hintergrund nichts steht, wird mit der Function das Hintergrund geändert

Set-WallPaper -Image $pfad 



}

if($ckb_nachw.Checked -eq $true){                                                                #Wiederherstellungspunkt wird erstellt

$datum = Get-Date

Checkpoint-Computer -Description $datum 

}





}

$btn_hintergrund_OnClick= 
{
#TODO: Place custom script here
$lsb_log.Items.Add("Bild wird geladen...")
try{
Invoke-WebRequest $txb_url.Text -OutFile ($pfad)                                                 #Wird versucht der Bild vom Link herunterzuladen
$bild = [System.Drawing.Image]::Fromfile($pfad)
$img_hintergrund.Image = $bild
$lsb_log.Items.Add("Bild wurde geladen")
}catch{                                                                                          #Wenn das nicht klappen würde, wird $frm_bildladen geöffnet

$frm_bildladen.ShowDialog() | Out-Null
$lsb_log.Items.Add("Bild konnte nicht geladen werden")
}

}



$btn_zuruecksetzen_OnClick= 
{
#TODO: Place custom script here
$form1.Close()

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 99
$System_Drawing_Size.Width = 318
$frm_pcname.ClientSize = $System_Drawing_Size
$frm_pcname.DataBindings.DefaultDataSourceUpdateMode = 0
$frm_pcname.Name = "frm_pcname"
$frm_pcname.Text = "PC Name"
$frm_pcname.add_Load($handler_frm_pcname_Load)


$btn_okpcname.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 113
$System_Drawing_Point.Y = 55
$btn_okpcname.Location = $System_Drawing_Point
$btn_okpcname.Name = "btn_okpcname"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$btn_okpcname.Size = $System_Drawing_Size
$btn_okpcname.TabIndex = 1
$btn_okpcname.Text = "OK"
$btn_okpcname.UseVisualStyleBackColor = $True
$btn_okpcname.add_Click($btn_okpcname_OnClick)

$frm_pcname.Controls.Add($btn_okpcname)

$lbl_pcname.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 44
$System_Drawing_Point.Y = 18
$lbl_pcname.Location = $System_Drawing_Point
$lbl_pcname.Name = "lbl_pcname"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 222
$lbl_pcname.Size = $System_Drawing_Size
$lbl_pcname.TabIndex = 0
$lbl_pcname.Text = "Bitte geben Sie einen gültigen Namen ein"

$frm_pcname.Controls.Add($lbl_pcname)


$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 144
$System_Drawing_Size.Width = 587
$frm_farbe.ClientSize = $System_Drawing_Size
$frm_farbe.DataBindings.DefaultDataSourceUpdateMode = 0
$frm_farbe.Name = "frm_farbe"
$frm_farbe.Text = "Farbe auswaehlen"

$lbl_farbe.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 21
$System_Drawing_Point.Y = 13
$lbl_farbe.Location = $System_Drawing_Point
$lbl_farbe.Name = "lbl_farbe"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 200
$lbl_farbe.Size = $System_Drawing_Size
$lbl_farbe.TabIndex = 6
$lbl_farbe.Text = "Waehlen Sie bitte eine Farbe aus:"

$frm_farbe.Controls.Add($lbl_farbe)

$btn_grau.BackColor = [System.Drawing.Color]::FromArgb(255,169,169,169)

$btn_grau.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 491
$System_Drawing_Point.Y = 56
$btn_grau.Location = $System_Drawing_Point
$btn_grau.Name = "btn_grau"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 60
$System_Drawing_Size.Width = 75
$btn_grau.Size = $System_Drawing_Size
$btn_grau.TabIndex = 5
$btn_grau.UseVisualStyleBackColor = $False
$btn_grau.add_Click($btn_grau_OnClick)

$frm_farbe.Controls.Add($btn_grau)

$btn_rot.BackColor = [System.Drawing.Color]::FromArgb(255,255,0,0)

$btn_rot.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 397
$System_Drawing_Point.Y = 56
$btn_rot.Location = $System_Drawing_Point
$btn_rot.Name = "btn_rot"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 61
$System_Drawing_Size.Width = 75
$btn_rot.Size = $System_Drawing_Size
$btn_rot.TabIndex = 4
$btn_rot.UseVisualStyleBackColor = $False
$btn_rot.add_Click($btn_rot_OnClick)

$frm_farbe.Controls.Add($btn_rot)

$btn_gelb.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,0)

$btn_gelb.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 301
$System_Drawing_Point.Y = 56
$btn_gelb.Location = $System_Drawing_Point
$btn_gelb.Name = "btn_gelb"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 62
$System_Drawing_Size.Width = 75
$btn_gelb.Size = $System_Drawing_Size
$btn_gelb.TabIndex = 3
$btn_gelb.UseVisualStyleBackColor = $False
$btn_gelb.add_Click($btn_gelb_OnClick)

$frm_farbe.Controls.Add($btn_gelb)

$btn_violett.BackColor = [System.Drawing.Color]::FromArgb(255,238,130,238)

$btn_violett.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 207
$System_Drawing_Point.Y = 56
$btn_violett.Location = $System_Drawing_Point
$btn_violett.Name = "btn_violett"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 62
$System_Drawing_Size.Width = 75
$btn_violett.Size = $System_Drawing_Size
$btn_violett.TabIndex = 2
$btn_violett.UseVisualStyleBackColor = $False
$btn_violett.add_Click($btn_violett_OnClick)

$frm_farbe.Controls.Add($btn_violett)

$btn_gruen.BackColor = [System.Drawing.Color]::FromArgb(255,0,255,0)

$btn_gruen.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 112
$System_Drawing_Point.Y = 56
$btn_gruen.Location = $System_Drawing_Point
$btn_gruen.Name = "btn_gruen"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 62
$System_Drawing_Size.Width = 75
$btn_gruen.Size = $System_Drawing_Size
$btn_gruen.TabIndex = 1
$btn_gruen.UseVisualStyleBackColor = $False
$btn_gruen.add_Click($btn_gruen_OnClick)

$frm_farbe.Controls.Add($btn_gruen)

$btn_blau.BackColor = [System.Drawing.Color]::FromArgb(255,30,144,255)

$btn_blau.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 21
$System_Drawing_Point.Y = 56
$btn_blau.Location = $System_Drawing_Point
$btn_blau.Name = "btn_blau"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 63
$System_Drawing_Size.Width = 75
$btn_blau.Size = $System_Drawing_Size
$btn_blau.TabIndex = 0
$btn_blau.UseVisualStyleBackColor = $False
$btn_blau.add_Click($btn_blau_OnClick)

$frm_farbe.Controls.Add($btn_blau)

$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 91
$System_Drawing_Size.Width = 429
$frm_bildladen.ClientSize = $System_Drawing_Size
$frm_bildladen.DataBindings.DefaultDataSourceUpdateMode = 0
$frm_bildladen.Name = "frm_bildladen"
$frm_bildladen.Text = "Bild"


$btn_OKbild.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 176
$System_Drawing_Point.Y = 56
$btn_OKbild.Location = $System_Drawing_Point
$btn_OKbild.Name = "btn_OKbild"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$btn_OKbild.Size = $System_Drawing_Size
$btn_OKbild.TabIndex = 1
$btn_OKbild.Text = "OK"
$btn_OKbild.UseVisualStyleBackColor = $True
$btn_OKbild.add_Click($btn_OKbild_OnClick)

$frm_bildladen.Controls.Add($btn_OKbild)

$lbl_bildladen.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 26
$System_Drawing_Point.Y = 18
$lbl_bildladen.Location = $System_Drawing_Point
$lbl_bildladen.Name = "lbl_bildladen"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 380
$lbl_bildladen.Size = $System_Drawing_Size
$lbl_bildladen.TabIndex = 0
$lbl_bildladen.Text = "Bitte geben Sie einen gültigen Link ein  (z.B. .png/.jpg)"

$frm_bildladen.Controls.Add($lbl_bildladen)


$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 125
$System_Drawing_Size.Width = 401
$frm_pass.ClientSize = $System_Drawing_Size
$frm_pass.DataBindings.DefaultDataSourceUpdateMode = 0
$frm_pass.Name = "frm_pass"
$frm_pass.Text = "Passwort"


$btn_OKpass.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 159
$System_Drawing_Point.Y = 76
$btn_OKpass.Location = $System_Drawing_Point
$btn_OKpass.Name = "btn_OKpass"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$btn_OKpass.Size = $System_Drawing_Size
$btn_OKpass.TabIndex = 1
$btn_OKpass.Text = "OK"
$btn_OKpass.UseVisualStyleBackColor = $True
$btn_OKpass.add_Click($btn_OKpass_OnClick)

$frm_pass.Controls.Add($btn_OKpass)

$lbl_passmeldung.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 33
$System_Drawing_Point.Y = 21
$lbl_passmeldung.Location = $System_Drawing_Point
$lbl_passmeldung.Name = "lbl_passmeldung"
$System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
$System_Windows_Forms_Padding.All = 4
$System_Windows_Forms_Padding.Bottom = 4
$System_Windows_Forms_Padding.Left = 4
$System_Windows_Forms_Padding.Right = 4
$System_Windows_Forms_Padding.Top = 4
$lbl_passmeldung.Padding = $System_Windows_Forms_Padding
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 62
$System_Drawing_Size.Width = 325
$lbl_passmeldung.Size = $System_Drawing_Size
$lbl_passmeldung.TabIndex = 0
$lbl_passmeldung.Text = "Bitte alle Daten eingeben. Geben Sie ein gültiges Passwort ein. (Das Passwort muss acht oder mehr Zeichen lang sein. Es muss Großbuchstaben, Kleinbuchstaben 0-9 und Sonderzeichen (!, $, #, %, usw.) enthalten."

$frm_pass.Controls.Add($lbl_passmeldung)


$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 81
$System_Drawing_Size.Width = 320
$frm_neustart.ClientSize = $System_Drawing_Size
$frm_neustart.DataBindings.DefaultDataSourceUpdateMode = 0
$frm_neustart.Name = "frm_neustart"
$frm_neustart.Text = "Neu starten"

$lbl_neustart.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$lbl_neustart.Location = $System_Drawing_Point
$lbl_neustart.Name = "lbl_neustart"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 296
$lbl_neustart.Size = $System_Drawing_Size
$lbl_neustart.TabIndex = 2
$lbl_neustart.Text = "Starten Sie den PC neu um die aenderungen vorzunehmen"

$frm_neustart.Controls.Add($lbl_neustart)


$btn_spaeter.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 155
$System_Drawing_Point.Y = 46
$btn_spaeter.Location = $System_Drawing_Point
$btn_spaeter.Name = "btn_spaeter"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 115
$btn_spaeter.Size = $System_Drawing_Size
$btn_spaeter.TabIndex = 1
$btn_spaeter.Text = "Später neu starten"
$btn_spaeter.UseVisualStyleBackColor = $True
$btn_spaeter.add_Click($btn_spaeter_OnClick)

$frm_neustart.Controls.Add($btn_spaeter)


$btn_neustarten.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 47
$System_Drawing_Point.Y = 46
$btn_neustarten.Location = $System_Drawing_Point
$btn_neustarten.Name = "btn_neustarten"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 104
$btn_neustarten.Size = $System_Drawing_Size
$btn_neustarten.TabIndex = 0
$btn_neustarten.Text = "Jetzt neu starten"
$btn_neustarten.UseVisualStyleBackColor = $True
$btn_neustarten.add_Click($btn_neustarten_OnClick)

$frm_neustart.Controls.Add($btn_neustarten)


$form1.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 487
$System_Drawing_Size.Width = 1004
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)
$form1.Name = "form1"
$form1.Text = "AutoSetup "


$btn_zuruecksetzen.DataBindings.DefaultDataSourceUpdateMode = 0
$btn_zuruecksetzen.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 717
$System_Drawing_Point.Y = 419
$btn_zuruecksetzen.Location = $System_Drawing_Point
$btn_zuruecksetzen.Name = "btn_zuruecksetzen"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 52
$System_Drawing_Size.Width = 273
$btn_zuruecksetzen.Size = $System_Drawing_Size
$btn_zuruecksetzen.TabIndex = 41
$btn_zuruecksetzen.Text = "Programm beenden"
$btn_zuruecksetzen.UseVisualStyleBackColor = $True
$btn_zuruecksetzen.add_Click($btn_zuruecksetzen_OnClick)

$form1.Controls.Add($btn_zuruecksetzen)


$grb_wiederherstellung.DataBindings.DefaultDataSourceUpdateMode = 0
$grb_wiederherstellung.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,1,3,1)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 717
$System_Drawing_Point.Y = 121
$grb_wiederherstellung.Location = $System_Drawing_Point
$grb_wiederherstellung.Name = "grb_wiederherstellung"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 119
$System_Drawing_Size.Width = 273
$grb_wiederherstellung.Size = $System_Drawing_Size
$grb_wiederherstellung.TabIndex = 40
$grb_wiederherstellung.TabStop = $False
$grb_wiederherstellung.Text = "Wiederherstellung"

$form1.Controls.Add($grb_wiederherstellung)

$ckb_nachw.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_nachw.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 70
$ckb_nachw.Location = $System_Drawing_Point
$ckb_nachw.Name = "ckb_nachw"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 35
$System_Drawing_Size.Width = 261
$ckb_nachw.Size = $System_Drawing_Size
$ckb_nachw.TabIndex = 1
$ckb_nachw.Text = "Wiederherstellungspunkt nach Ausführung erstellen"
$ckb_nachw.UseVisualStyleBackColor = $True

$grb_wiederherstellung.Controls.Add($ckb_nachw)


$ckb_wvorher.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_wvorher.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 29
$ckb_wvorher.Location = $System_Drawing_Point
$ckb_wvorher.Name = "ckb_wvorher"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 42
$System_Drawing_Size.Width = 259
$ckb_wvorher.Size = $System_Drawing_Size
$ckb_wvorher.TabIndex = 0
$ckb_wvorher.Text = "Wiederherstellungspunkt vor Ausführung erstellen"
$ckb_wvorher.UseVisualStyleBackColor = $True

$grb_wiederherstellung.Controls.Add($ckb_wvorher)



$grb_farbe.DataBindings.DefaultDataSourceUpdateMode = 0
$grb_farbe.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,1,3,1)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 717
$System_Drawing_Point.Y = 15
$grb_farbe.Location = $System_Drawing_Point
$grb_farbe.Name = "grb_farbe"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 99
$System_Drawing_Size.Width = 273
$grb_farbe.Size = $System_Drawing_Size
$grb_farbe.TabIndex = 39
$grb_farbe.TabStop = $False
$grb_farbe.Text = "Farben"

$form1.Controls.Add($grb_farbe)

$ckb_darkmode.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_darkmode.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 68
$ckb_darkmode.Location = $System_Drawing_Point
$ckb_darkmode.Name = "ckb_darkmode"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 199
$ckb_darkmode.Size = $System_Drawing_Size
$ckb_darkmode.TabIndex = 2
$ckb_darkmode.Text = "Darkmode einschalten"
$ckb_darkmode.UseVisualStyleBackColor = $True

$grb_farbe.Controls.Add($ckb_darkmode)


$btn_standardfarbeloeschen.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 241
$System_Drawing_Point.Y = 20
$btn_standardfarbeloeschen.Location = $System_Drawing_Point
$btn_standardfarbeloeschen.Name = "btn_standardfarbeloeschen"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 42
$System_Drawing_Size.Width = 25
$btn_standardfarbeloeschen.Size = $System_Drawing_Size
$btn_standardfarbeloeschen.TabIndex = 1
$btn_standardfarbeloeschen.Text = "X"
$btn_standardfarbeloeschen.UseVisualStyleBackColor = $True
$btn_standardfarbeloeschen.add_Click($btn_standardfarbeloeschen_OnClick)

$grb_farbe.Controls.Add($btn_standardfarbeloeschen)


$btn_standardfarbe.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 20
$btn_standardfarbe.Location = $System_Drawing_Point
$btn_standardfarbe.Name = "btn_standardfarbe"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 42
$System_Drawing_Size.Width = 229
$btn_standardfarbe.Size = $System_Drawing_Size
$btn_standardfarbe.TabIndex = 0
$btn_standardfarbe.Text = "Standard Farbe auswählen"
$btn_standardfarbe.UseVisualStyleBackColor = $True
$btn_standardfarbe.add_Click($btn_standardfarbe_OnClick)

$grb_farbe.Controls.Add($btn_standardfarbe)



$grb_applikation.DataBindings.DefaultDataSourceUpdateMode = 0
$grb_applikation.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,1,3,1)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 15
$grb_applikation.Location = $System_Drawing_Point
$grb_applikation.Name = "grb_applikation"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 460
$System_Drawing_Size.Width = 217
$grb_applikation.Size = $System_Drawing_Size
$grb_applikation.TabIndex = 38
$grb_applikation.TabStop = $False
$grb_applikation.Text = "Applikationen installieren"

$form1.Controls.Add($grb_applikation)

$ckb_chocolatey.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_chocolatey.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 21
$ckb_chocolatey.Location = $System_Drawing_Point
$ckb_chocolatey.Name = "ckb_chocolatey"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 123
$ckb_chocolatey.Size = $System_Drawing_Size
$ckb_chocolatey.TabIndex = 32
$ckb_chocolatey.Text = "Chocolatey"
$ckb_chocolatey.UseVisualStyleBackColor = $True

$grb_applikation.Controls.Add($ckb_chocolatey)

$lbl_browser.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_browser.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 10
$System_Drawing_Point.Y = 46
$lbl_browser.Location = $System_Drawing_Point
$lbl_browser.Name = "lbl_browser"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 100
$lbl_browser.Size = $System_Drawing_Size
$lbl_browser.TabIndex = 0
$lbl_browser.Text = "Browser"

$grb_applikation.Controls.Add($lbl_browser)


$ckb_firefox.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_firefox.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 64
$ckb_firefox.Location = $System_Drawing_Point
$ckb_firefox.Name = "ckb_firefox"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$ckb_firefox.Size = $System_Drawing_Size
$ckb_firefox.TabIndex = 2
$ckb_firefox.Text = "Firefox"
$ckb_firefox.UseVisualStyleBackColor = $True
$ckb_firefox.add_CheckedChanged($handler_ckb_firefox_CheckedChanged)

$grb_applikation.Controls.Add($ckb_firefox)


$ckb_opera.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_opera.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 85
$ckb_opera.Location = $System_Drawing_Point
$ckb_opera.Name = "ckb_opera"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 149
$ckb_opera.Size = $System_Drawing_Size
$ckb_opera.TabIndex = 3
$ckb_opera.Text = "Opera (Gaming)"
$ckb_opera.UseVisualStyleBackColor = $True
$ckb_opera.add_CheckedChanged($handler_ckb_opera_CheckedChanged)

$grb_applikation.Controls.Add($ckb_opera)


$ckb_chrome.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_chrome.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 105
$ckb_chrome.Location = $System_Drawing_Point
$ckb_chrome.Name = "ckb_chrome"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 147
$ckb_chrome.Size = $System_Drawing_Size
$ckb_chrome.TabIndex = 1
$ckb_chrome.Text = "Google Chrome"
$ckb_chrome.UseVisualStyleBackColor = $True
$ckb_chrome.add_CheckedChanged($handler_ckb_chrome_CheckedChanged)

$grb_applikation.Controls.Add($ckb_chrome)

$lbl_archiv.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_archiv.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 10
$System_Drawing_Point.Y = 135
$lbl_archiv.Location = $System_Drawing_Point
$lbl_archiv.Name = "lbl_archiv"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 100
$lbl_archiv.Size = $System_Drawing_Size
$lbl_archiv.TabIndex = 5
$lbl_archiv.Text = "Archiv"

$grb_applikation.Controls.Add($lbl_archiv)


$ckb_winrar.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_winrar.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 156
$ckb_winrar.Location = $System_Drawing_Point
$ckb_winrar.Name = "ckb_winrar"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 104
$ckb_winrar.Size = $System_Drawing_Size
$ckb_winrar.TabIndex = 6
$ckb_winrar.Text = "WinRAR"
$ckb_winrar.UseVisualStyleBackColor = $True
$ckb_winrar.add_CheckedChanged($handler_ckb_winrar_CheckedChanged)

$grb_applikation.Controls.Add($ckb_winrar)


$ckb_7zip.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_7zip.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 177
$ckb_7zip.Location = $System_Drawing_Point
$ckb_7zip.Name = "ckb_7zip"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$ckb_7zip.Size = $System_Drawing_Size
$ckb_7zip.TabIndex = 7
$ckb_7zip.Text = "7Zip"
$ckb_7zip.UseVisualStyleBackColor = $True
$ckb_7zip.add_CheckedChanged($handler_ckb_7zip_CheckedChanged)

$grb_applikation.Controls.Add($ckb_7zip)

$lbl_chat.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_chat.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 10
$System_Drawing_Point.Y = 204
$lbl_chat.Location = $System_Drawing_Point
$lbl_chat.Name = "lbl_chat"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 100
$lbl_chat.Size = $System_Drawing_Size
$lbl_chat.TabIndex = 8
$lbl_chat.Text = "Chat"

$grb_applikation.Controls.Add($lbl_chat)


$ckb_download.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_download.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 5
$System_Drawing_Point.Y = 430
$ckb_download.Location = $System_Drawing_Point
$ckb_download.Name = "ckb_download"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 156
$ckb_download.Size = $System_Drawing_Size
$ckb_download.TabIndex = 19
$ckb_download.Text = "Download Manager"
$ckb_download.UseVisualStyleBackColor = $True
$ckb_download.add_CheckedChanged($handler_ckb_download_CheckedChanged)

$grb_applikation.Controls.Add($ckb_download)


$ckb_backup.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_backup.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 389
$ckb_backup.Location = $System_Drawing_Point
$ckb_backup.Name = "ckb_backup"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 183
$ckb_backup.Size = $System_Drawing_Size
$ckb_backup.TabIndex = 21
$ckb_backup.Text = "Google Backup and Sync"
$ckb_backup.UseVisualStyleBackColor = $True

$grb_applikation.Controls.Add($ckb_backup)


$ckb_geek.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_geek.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 5
$System_Drawing_Point.Y = 409
$ckb_geek.Location = $System_Drawing_Point
$ckb_geek.Name = "ckb_geek"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 148
$ckb_geek.Size = $System_Drawing_Size
$ckb_geek.TabIndex = 18
$ckb_geek.Text = "Geek Uninstaller"
$ckb_geek.UseVisualStyleBackColor = $True
$ckb_geek.add_CheckedChanged($handler_ckb_geek_CheckedChanged)

$grb_applikation.Controls.Add($ckb_geek)


$ckb_teams.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_teams.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 221
$ckb_teams.Location = $System_Drawing_Point
$ckb_teams.Name = "ckb_teams"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$ckb_teams.Size = $System_Drawing_Size
$ckb_teams.TabIndex = 9
$ckb_teams.Text = "Teams"
$ckb_teams.UseVisualStyleBackColor = $True
$ckb_teams.add_CheckedChanged($handler_ckb_teams_CheckedChanged)

$grb_applikation.Controls.Add($ckb_teams)


$ckb_discord.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_discord.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 240
$ckb_discord.Location = $System_Drawing_Point
$ckb_discord.Name = "ckb_discord"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$ckb_discord.Size = $System_Drawing_Size
$ckb_discord.TabIndex = 10
$ckb_discord.Text = "Discord"
$ckb_discord.UseVisualStyleBackColor = $True
$ckb_discord.add_CheckedChanged($handler_ckb_discord_CheckedChanged)

$grb_applikation.Controls.Add($ckb_discord)


$ckb_zoom.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_zoom.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 261
$ckb_zoom.Location = $System_Drawing_Point
$ckb_zoom.Name = "ckb_zoom"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$ckb_zoom.Size = $System_Drawing_Size
$ckb_zoom.TabIndex = 11
$ckb_zoom.Text = "Zoom"
$ckb_zoom.UseVisualStyleBackColor = $True
$ckb_zoom.add_CheckedChanged($handler_ckb_zoom_CheckedChanged)

$grb_applikation.Controls.Add($ckb_zoom)

$lbl_sonstige.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_sonstige.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 10
$System_Drawing_Point.Y = 370
$lbl_sonstige.Location = $System_Drawing_Point
$lbl_sonstige.Name = "lbl_sonstige"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lbl_sonstige.Size = $System_Drawing_Size
$lbl_sonstige.TabIndex = 17
$lbl_sonstige.Text = "Sonstige"
$lbl_sonstige.add_Click($handler_label8_Click)

$grb_applikation.Controls.Add($lbl_sonstige)

$lbl_medien.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_medien.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 10
$System_Drawing_Point.Y = 288
$lbl_medien.Location = $System_Drawing_Point
$lbl_medien.Name = "lbl_medien"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 100
$lbl_medien.Size = $System_Drawing_Size
$lbl_medien.TabIndex = 12
$lbl_medien.Text = "Medien"

$grb_applikation.Controls.Add($lbl_medien)


$ckb_adobe.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_adobe.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 345
$ckb_adobe.Location = $System_Drawing_Point
$ckb_adobe.Name = "ckb_adobe"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 133
$ckb_adobe.Size = $System_Drawing_Size
$ckb_adobe.TabIndex = 15
$ckb_adobe.Text = "Adobe Reader"
$ckb_adobe.UseVisualStyleBackColor = $True
$ckb_adobe.add_CheckedChanged($handler_ckb_adobe_CheckedChanged)

$grb_applikation.Controls.Add($ckb_adobe)


$ckb_paintnet.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_paintnet.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 305
$ckb_paintnet.Location = $System_Drawing_Point
$ckb_paintnet.Name = "ckb_paintnet"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$ckb_paintnet.Size = $System_Drawing_Size
$ckb_paintnet.TabIndex = 13
$ckb_paintnet.Text = "Paint.NET"
$ckb_paintnet.UseVisualStyleBackColor = $True
$ckb_paintnet.add_CheckedChanged($handler_ckb_paintnet_CheckedChanged)

$grb_applikation.Controls.Add($ckb_paintnet)


$ckb_vlc.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_vlc.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 324
$ckb_vlc.Location = $System_Drawing_Point
$ckb_vlc.Name = "ckb_vlc"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$ckb_vlc.Size = $System_Drawing_Size
$ckb_vlc.TabIndex = 14
$ckb_vlc.Text = "VLC"
$ckb_vlc.UseVisualStyleBackColor = $True
$ckb_vlc.add_CheckedChanged($handler_ckb_vlc_CheckedChanged)

$grb_applikation.Controls.Add($ckb_vlc)



$grb_benutzer.DataBindings.DefaultDataSourceUpdateMode = 0
$grb_benutzer.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,1,3,1)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 479
$System_Drawing_Point.Y = 96
$grb_benutzer.Location = $System_Drawing_Point
$grb_benutzer.Name = "grb_benutzer"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 219
$System_Drawing_Size.Width = 228
$grb_benutzer.Size = $System_Drawing_Size
$grb_benutzer.TabIndex = 37
$grb_benutzer.TabStop = $False
$grb_benutzer.Text = "Neuer Benutzer anlegen"

$form1.Controls.Add($grb_benutzer)

$ckb_user.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 181
$System_Drawing_Point.Y = -1
$ckb_user.Location = $System_Drawing_Point
$ckb_user.Name = "ckb_user"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 19
$System_Drawing_Size.Width = 15
$ckb_user.Size = $System_Drawing_Size
$ckb_user.TabIndex = 10
$ckb_user.UseVisualStyleBackColor = $True

$grb_benutzer.Controls.Add($ckb_user)

$txb_nachname.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 112
$System_Drawing_Point.Y = 39
$txb_nachname.Location = $System_Drawing_Point
$txb_nachname.Name = "txb_nachname"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 22
$System_Drawing_Size.Width = 103
$txb_nachname.Size = $System_Drawing_Size
$txb_nachname.TabIndex = 9

$grb_benutzer.Controls.Add($txb_nachname)

$lbl_nachname.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_nachname.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 111
$System_Drawing_Point.Y = 21
$lbl_nachname.Location = $System_Drawing_Point
$lbl_nachname.Name = "lbl_nachname"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lbl_nachname.Size = $System_Drawing_Size
$lbl_nachname.TabIndex = 8
$lbl_nachname.Text = "Nachname:"

$grb_benutzer.Controls.Add($lbl_nachname)


$ckb_passaendern.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_passaendern.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",8.25,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 180
$ckb_passaendern.Location = $System_Drawing_Point
$ckb_passaendern.Name = "ckb_passaendern"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 215
$ckb_passaendern.Size = $System_Drawing_Size
$ckb_passaendern.TabIndex = 7
$ckb_passaendern.Text = "Benutzer kann das Passwort nicht aendern"
$ckb_passaendern.UseVisualStyleBackColor = $True

$grb_benutzer.Controls.Add($ckb_passaendern)


$ckb_aktiv.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_aktiv.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 151
$ckb_aktiv.Location = $System_Drawing_Point
$ckb_aktiv.Name = "ckb_aktiv"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$ckb_aktiv.Size = $System_Drawing_Size
$ckb_aktiv.TabIndex = 6
$ckb_aktiv.Text = "Aktiv"
$ckb_aktiv.UseVisualStyleBackColor = $True

$grb_benutzer.Controls.Add($ckb_aktiv)

$txb_pass.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 123
$txb_pass.Location = $System_Drawing_Point
$txb_pass.Name = "txb_pass"
$txb_pass.PasswordChar = '*'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 22
$System_Drawing_Size.Width = 208
$txb_pass.Size = $System_Drawing_Size
$txb_pass.TabIndex = 5

$grb_benutzer.Controls.Add($txb_pass)

$lbl_pass.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_pass.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 5
$System_Drawing_Point.Y = 107
$lbl_pass.Location = $System_Drawing_Point
$lbl_pass.Name = "lbl_pass"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lbl_pass.Size = $System_Drawing_Size
$lbl_pass.TabIndex = 4
$lbl_pass.Text = "Passwort:"

$grb_benutzer.Controls.Add($lbl_pass)

$txb_user.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 82
$txb_user.Location = $System_Drawing_Point
$txb_user.Name = "txb_user"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 22
$System_Drawing_Size.Width = 208
$txb_user.Size = $System_Drawing_Size
$txb_user.TabIndex = 3

$grb_benutzer.Controls.Add($txb_user)

$lbl_user.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_user.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 5
$System_Drawing_Point.Y = 64
$lbl_user.Location = $System_Drawing_Point
$lbl_user.Name = "lbl_user"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lbl_user.Size = $System_Drawing_Size
$lbl_user.TabIndex = 2
$lbl_user.Text = "Anmeldename:"

$grb_benutzer.Controls.Add($lbl_user)

$txb_vorname.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 39
$txb_vorname.Location = $System_Drawing_Point
$txb_vorname.Name = "txb_vorname"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 22
$System_Drawing_Size.Width = 99
$txb_vorname.Size = $System_Drawing_Size
$txb_vorname.TabIndex = 1

$grb_benutzer.Controls.Add($txb_vorname)

$lbl_vorname.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_vorname.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 5
$System_Drawing_Point.Y = 21
$lbl_vorname.Location = $System_Drawing_Point
$lbl_vorname.Name = "lbl_vorname"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$lbl_vorname.Size = $System_Drawing_Size
$lbl_vorname.TabIndex = 0
$lbl_vorname.Text = "Vorname:"
$lbl_vorname.add_Click($handler_label2_Click)

$grb_benutzer.Controls.Add($lbl_vorname)



$grb_name.DataBindings.DefaultDataSourceUpdateMode = 0
$grb_name.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,1,3,1)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 478
$System_Drawing_Point.Y = 15
$grb_name.Location = $System_Drawing_Point
$grb_name.Name = "grb_name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 74
$System_Drawing_Size.Width = 229
$grb_name.Size = $System_Drawing_Size
$grb_name.TabIndex = 36
$grb_name.TabStop = $False
$grb_name.Text = "PC Name ändern"

$form1.Controls.Add($grb_name)

$ckb_name.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 135
$System_Drawing_Point.Y = -3
$ckb_name.Location = $System_Drawing_Point
$ckb_name.Name = "ckb_name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 18
$ckb_name.Size = $System_Drawing_Size
$ckb_name.TabIndex = 36
$ckb_name.UseVisualStyleBackColor = $True

$grb_name.Controls.Add($ckb_name)

$txb_name.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 41
$txb_name.Location = $System_Drawing_Point
$txb_name.Name = "txb_name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 22
$System_Drawing_Size.Width = 216
$txb_name.Size = $System_Drawing_Size
$txb_name.TabIndex = 35

$grb_name.Controls.Add($txb_name)

$lbl_name.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_name.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 17
$lbl_name.Location = $System_Drawing_Point
$lbl_name.Name = "lbl_name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 137
$lbl_name.Size = $System_Drawing_Size
$lbl_name.TabIndex = 34
$lbl_name.Text = "Neuer Name eingeben:"

$grb_name.Controls.Add($lbl_name)



$checkBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$checkBox1.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 630
$System_Drawing_Point.Y = 56
$checkBox1.Location = $System_Drawing_Point
$checkBox1.Name = "checkBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 152
$checkBox1.Size = $System_Drawing_Size
$checkBox1.TabIndex = 33
$checkBox1.UseVisualStyleBackColor = $True

$form1.Controls.Add($checkBox1)

$lsb_log.DataBindings.DefaultDataSourceUpdateMode = 0
$lsb_log.FormattingEnabled = $True
$lsb_log.ItemHeight = 15
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 235
$System_Drawing_Point.Y = 321
$lsb_log.Location = $System_Drawing_Point
$lsb_log.Name = "lsb_log"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 154
$System_Drawing_Size.Width = 472
$lsb_log.Size = $System_Drawing_Size
$lsb_log.TabIndex = 31
$lsb_log.add_SelectedIndexChanged($handler_lsb_log_SelectedIndexChanged)

$form1.Controls.Add($lsb_log)


$btn_laden.DataBindings.DefaultDataSourceUpdateMode = 0
$btn_laden.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 717
$System_Drawing_Point.Y = 361
$btn_laden.Location = $System_Drawing_Point
$btn_laden.Name = "btn_laden"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 52
$System_Drawing_Size.Width = 273
$btn_laden.Size = $System_Drawing_Size
$btn_laden.TabIndex = 25
$btn_laden.Text = "Konfiguration laden"
$btn_laden.UseVisualStyleBackColor = $True
$btn_laden.add_Click($btn_laden_OnClick)

$form1.Controls.Add($btn_laden)


$btn_speichern.DataBindings.DefaultDataSourceUpdateMode = 0
$btn_speichern.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 717
$System_Drawing_Point.Y = 303
$btn_speichern.Location = $System_Drawing_Point
$btn_speichern.Name = "btn_speichern"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 52
$System_Drawing_Size.Width = 273
$btn_speichern.Size = $System_Drawing_Size
$btn_speichern.TabIndex = 24
$btn_speichern.Text = "Konfiguration speichern"
$btn_speichern.UseVisualStyleBackColor = $True
$btn_speichern.add_Click($btn_speichern_OnClick)

$form1.Controls.Add($btn_speichern)


$btn_anwenden.DataBindings.DefaultDataSourceUpdateMode = 0
$btn_anwenden.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",12,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 717
$System_Drawing_Point.Y = 246
$btn_anwenden.Location = $System_Drawing_Point
$btn_anwenden.Name = "btn_anwenden"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 52
$System_Drawing_Size.Width = 273
$btn_anwenden.Size = $System_Drawing_Size
$btn_anwenden.TabIndex = 23
$btn_anwenden.Text = "Anwenden"
$btn_anwenden.UseVisualStyleBackColor = $True
$btn_anwenden.add_Click($btn_anwenden_OnClick)

$form1.Controls.Add($btn_anwenden)


$grb_hintergrund.DataBindings.DefaultDataSourceUpdateMode = 0
$grb_hintergrund.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,1,3,1)
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 235
$System_Drawing_Point.Y = 15
$grb_hintergrund.Location = $System_Drawing_Point
$grb_hintergrund.Name = "grb_hintergrund"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 300
$System_Drawing_Size.Width = 237
$grb_hintergrund.Size = $System_Drawing_Size
$grb_hintergrund.TabIndex = 35
$grb_hintergrund.TabStop = $False
$grb_hintergrund.Text = "Hintergrundbild festlegen"

$form1.Controls.Add($grb_hintergrund)
$lbl_hintergrund.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_hintergrund.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 5
$System_Drawing_Point.Y = 20
$lbl_hintergrund.Location = $System_Drawing_Point
$lbl_hintergrund.Name = "lbl_hintergrund"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 195
$lbl_hintergrund.Size = $System_Drawing_Size
$lbl_hintergrund.TabIndex = 27
$lbl_hintergrund.Text = "URL einer JPG Datei einfügen:"
$lbl_hintergrund.add_Click($handler_lbl_hintergrund_Click)

$grb_hintergrund.Controls.Add($lbl_hintergrund)

$txb_url.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 8
$System_Drawing_Point.Y = 48
$txb_url.Location = $System_Drawing_Point
$txb_url.Name = "txb_url"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 22
$System_Drawing_Size.Width = 223
$txb_url.Size = $System_Drawing_Size
$txb_url.TabIndex = 29
$txb_url.add_TextChanged($handler_txb_url_TextChanged)

$grb_hintergrund.Controls.Add($txb_url)


$btn_hintergrund.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 8
$System_Drawing_Point.Y = 81
$btn_hintergrund.Location = $System_Drawing_Point
$btn_hintergrund.Name = "btn_hintergrund"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 33
$System_Drawing_Size.Width = 223
$btn_hintergrund.Size = $System_Drawing_Size
$btn_hintergrund.TabIndex = 30
$btn_hintergrund.Text = "Bild laden"
$btn_hintergrund.UseVisualStyleBackColor = $True
$btn_hintergrund.add_Click($btn_hintergrund_OnClick)

$grb_hintergrund.Controls.Add($btn_hintergrund)


$ckb_hintergrund.DataBindings.DefaultDataSourceUpdateMode = 0
$ckb_hintergrund.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9.75,1,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 191
$System_Drawing_Point.Y = -3
$ckb_hintergrund.Location = $System_Drawing_Point
$ckb_hintergrund.Name = "ckb_hintergrund"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 18
$ckb_hintergrund.Size = $System_Drawing_Size
$ckb_hintergrund.TabIndex = 26
$ckb_hintergrund.UseVisualStyleBackColor = $True

$grb_hintergrund.Controls.Add($ckb_hintergrund)


$img_hintergrund.BorderStyle = 1
$img_hintergrund.DataBindings.DefaultDataSourceUpdateMode = 0



$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 8
$System_Drawing_Point.Y = 120
$img_hintergrund.Location = $System_Drawing_Point
$img_hintergrund.Name = "img_hintergrund"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 166
$System_Drawing_Size.Width = 223
$img_hintergrund.Size = $System_Drawing_Size
$img_hintergrund.TabIndex = 28
$img_hintergrund.TabStop = $False
$img_hintergrund.add_Click($handler_pictureBox2_Click)
$img_hintergrund.SizeMode = [System.Windows.Forms.PictureBoxSizeMode]::Zoom

$grb_hintergrund.Controls.Add($img_hintergrund)


#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
